default-resources:
    - runtime=60
    - mem_mb=1024
    - disk_mb=100000
set-threads:
    - single_core_rule=1
    - multi_core_rule=16
set-resources:
    - high_memory_rule: mem_mb=12000
    - long_running_rule: runtime=1200
jobname: "{rule}-{wildcards}"
