#!/usr/bin/env bash

set -euo pipefail

snakemake \
    --use-conda \
    --conda-frontend mamba \
    --rerun-incomplete \
    --jobs 100 \
    --cores 24 \
    --keep-going \
    --notemp \
    --slurm \
    --profile config/profile \
    --latency-wait 60 \
    "$@"
