# quantify: environment to quantify a dereplicated magalogue
---
name: quantify
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.5.1
  - coverm=0.6.1
  - r-argparse=2.2.2
  - r-tidyverse=2.0.0
  - samtools=1.18
