# Paths to used docker container
---
annotate: "docker://fischuu/hrp_annotate:0.2"
assemble: "docker://fischuu/hrp_assemble:0.2"
checkm2: "docker://fischuu/hrp_checkm2:0.1"
concoct: "docker://fischuu/hrp_concoct:0.1"
dram: "docker://fischuu/hrp_dram:0.1"
gtdbtk: "docker://fischuu/hrp_gtdbtk:0.2"
helpers: "docker://fischuu/hrp_helpers:0.1"
phyloflash: "docker://fischuu/hrp_phyloflash:0.1"
preprocess: "docker://fischuu/hrp_preprocess:0.4"
quantify: "docker://fischuu/hrp_quantify:0.1"
reads: "docker://fischuu/hrp_reads:0.2"
reference: "docker://fischuu/hrp_reference:0.1"
report: "docker://fischuu/hrp_report:0.1"
vamb: "docker://fischuu/hrp_vamb:0.1"
virify: "docker://fischuu/hrp_virify:0.1"
