# assembly: environment to assemble mags
---
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - biopython=1.81
  - bowtie2=2.5.1
  - checkm-genome=1.2.2
  - coreutils=9.4
  - drep=3.4.3
  - hmmer=3.3.2
  - maxbin2=2.2.7
  - megahit=1.2.9
  - metabat2=2.15
  - pandas=2.1.2
  - parallel=20230922
  - pigz=2.8
  - prodigal=2.6.3
  - quast=5.2.0
  - r-argparse=2.2.2
  - r-funr=0.3.2
  - r-optparse=1.7.3
  - r-tidyverse=2.0.0
  - rename=1.601
  - samtools=1.18
  - seqtk=1.4
