executor: cluster-generic
jobs: 5
default-resources:
    time: 2
    mem_per_cpu: 4000
    cpu_per_task: 1
    partition: "test"
    slurm_account: "project_2009831"
cluster-generic-submit-cmd: "sbatch --time {resources.time} --account={resources.slurm_account} --job-name='{jobid}-{rule}' --tasks-per-node=1 --cpus-per-task={resources.cpu_per_task} --mem-per-cpu={resources.mem_per_cpu} --partition={resources.partition}"
