# reads: environment to preprocess reads before mag assembly
---
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.5.1
  - csvkit=1.3.0
  - fastp=0.23.4
  - fastqc=0.12.1
  - gzip=1.10
  - kraken2=2.1.3
  - nonpareil=3.4.1
  - pigz=2.8
  - r-argparse=2.2.2
  - r-nonpareil=3.4.0
  - r-tidyverse=2.0.0
  - rsync=3.2.7
  - samtools=1.18
  - singlem=0.16.0
